train:
  batch_size_per_gpu: 16
  dataset_path: /yinghepool/yinghe/datalist/v0.9/v0.9.1-CT-chest-ProjectX-2d.json
  output_dir: .
  saveckp_freq: 20
  seed: 0
  num_workers: 24
  OFFICIAL_EPOCH_LENGTH: 1000

evaluation:
  eval_period_iterations: 5000

optim:
  epochs: 200
  weight_decay: 0.005
  weight_decay_end: 0.1
  base_lr: 0.002  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 10
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999

## dataset
crops:
  global_crops_size: 512
  global_crops_scale:
  - 0.8
  - 1.0
  local_crops_size: 160
  local_crops_number: 8
  local_crops_scale:
  - 0.2
  - 0.4


## MODEL
student:
  arch: swin_large
  in_chans: 1
  patch_size: 8
  block_chunks: 1
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 25

## HEAD
dino:
  loss_weight: 1.0
  head_nlayers: 3
  head_hidden_dim: 2048
  head_bottleneck_dim: 256
  head_n_prototypes: 65536
  koleo_loss_weight: 0.1
ibot:
  separate_head: false
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.2
  - 0.5
  head_nlayers: 3
  head_hidden_dim: 2048
  head_bottleneck_dim: 256
  head_n_prototypes: 65536



  